// Per-character configuration: appearance, body proportions, stats, special move.
// Heights are in "Babylon units" (~ meters). Colors are CSS hex.
//
// Visual inspiration is the Mario-family from photos/bodies.png, but bodies are
// procedurally built from primitives so we can animate them.

// Vite injects BASE_URL at build time. Locally it is '/'; on GitHub Pages
// it becomes '/BudGame2026/' so the absolute asset paths still resolve.
const B = import.meta.env.BASE_URL;

export const CHARACTER_IDS = ['pat', 'bud', 'seb', 'nico'];

export const CHARACTERS = {
  pat: {
    id: 'pat',
    name: 'PAT',
    inspiration: 'Mario',
    facePath: `${B}faces/pat.png`,
    headPath: `${B}heads/pat.jpg`,
    // Colors
    shirt: '#d62828',
    cap: '#d62828',
    overalls: '#1d3557',
    overallsAccent: '#ffd60a',
    shoes: '#4a1f00',
    gloves: '#ffffff',
    skin: '#f3c89a',
    mustacheColor: '#1a1a1a',
    noseColor: '#e6a47a',
    // Proportions
    bodyHeight: 1.05,
    bodyWidth: 1.10,
    bodyDepth: 0.85,
    headRadius: 0.48,
    bellyRadius: 0.34,         // belly bump (kept modest by default; scales during special)
    bellyForward: 0.45,
    armLength: 1.0,
    armRadius: 0.14,
    legLength: 0.95,
    legRadius: 0.20,
    legSpread: 0.22,
    noseSize: 0.16,
    noseLength: 0.22,
    moveSpeed: 5.0,
    jumpPower: 9.5,
    weight: 1.0,
    special: 'belly',
    tagline: 'COUP DE BIDE !',
  },
  bud: {
    id: 'bud',
    name: 'BUD',
    inspiration: 'Luigi',
    facePath: `${B}faces/bud.png`,
    headPath: `${B}heads/bud.jpg`,
    shirt: '#2d8a3e',
    cap: '#2d8a3e',
    overalls: '#1d3557',
    overallsAccent: '#ffd60a',
    shoes: '#4a1f00',
    gloves: '#ffffff',
    skin: '#f3c89a',
    mustacheColor: '#1a1a1a',
    noseColor: '#e6a47a',
    bodyHeight: 1.20,
    bodyWidth: 0.85,
    bodyDepth: 0.70,
    headRadius: 0.45,
    bellyRadius: 0.22,
    bellyForward: 0.40,
    armLength: 1.18,
    armRadius: 0.12,
    legLength: 1.20,
    legRadius: 0.17,
    legSpread: 0.20,
    noseSize: 0.18,
    noseLength: 0.28,
    moveSpeed: 5.5,
    jumpPower: 13.0,
    weight: 0.85,
    special: 'jumpkick',
    tagline: 'COUP DE PIED SAUTÉ !',
  },
  seb: {
    id: 'seb',
    name: 'SEB',
    inspiration: 'Wario',
    facePath: `${B}faces/seb.png`,
    headPath: `${B}heads/seb.jpg`,
    shirt: '#fcbf49',
    cap: '#fcbf49',
    overalls: '#7209b7',
    overallsAccent: '#ffd60a',
    shoes: '#2d6a4f',
    gloves: '#ffffff',
    skin: '#f3c89a',
    mustacheColor: '#1a1a1a',
    noseColor: '#d18a6a',
    bodyHeight: 1.00,
    bodyWidth: 1.30,
    bodyDepth: 1.00,
    headRadius: 0.52,
    bellyRadius: 0.55,         // bigger belly
    bellyForward: 0.55,
    armLength: 0.95,
    armRadius: 0.18,
    legLength: 0.80,
    legRadius: 0.24,
    legSpread: 0.24,
    noseSize: 0.30,
    noseLength: 0.40,
    moveSpeed: 4.0,
    jumpPower: 7.5,
    weight: 1.3,
    special: 'nose',
    tagline: 'COUP DE PIF !',
  },
  nico: {
    id: 'nico',
    name: 'NICO',
    inspiration: 'Waluigi',
    facePath: `${B}faces/nico.png`,
    headPath: `${B}heads/nico.jpg`,
    shirt: '#7209b7',
    cap: '#7209b7',
    overalls: '#1a1a2e',
    overallsAccent: '#ffd60a',
    shoes: '#fb5607',
    gloves: '#ffffff',
    skin: '#f3c89a',
    mustacheColor: '#1a1a1a',
    noseColor: '#e6a47a',
    bodyHeight: 1.30,
    bodyWidth: 0.80,
    bodyDepth: 0.65,
    headRadius: 0.42,
    bellyRadius: 0.18,
    bellyForward: 0.35,
    armLength: 1.30,
    armRadius: 0.11,
    legLength: 1.35,
    legRadius: 0.14,
    legSpread: 0.18,
    noseSize: 0.13,
    noseLength: 0.45,
    moveSpeed: 5.5,
    jumpPower: 11.0,
    weight: 0.9,
    special: 'rock',
    tagline: 'LANCER DE CAILLOU !',
  },
};
